# Generated by Django 5.0.7 on 2024-07-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skills",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("linkedin", "Linkedin"),
                            ("personal_website", "Personal Website"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
                "db_table": "contact_infos",
                "unique_together": {("value", "contact_type")},
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(db_index=True, max_length=100)),
                ("subtitle", models.CharField(db_index=True, max_length=200)),
                ("version", models.CharField(max_length=5)),
                (
                    "contact_information",
                    models.ManyToManyField(related_name="+", to="resume.contactinfo"),
                ),
                ("skills", models.ManyToManyField(related_name="+", to="resume.skill")),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "db_table": "resumes",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "title",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="resume.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Section",
                "db_table": "sections",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="resume.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Item",
                "verbose_name_plural": "Section Items",
                "db_table": "section_items",
                "ordering": ["order", "pk"],
            },
        ),
    ]
